# Fuzzel Colours

[colors]
background=15050fff
text=e1e2ebff
prompt=424753ff
placeholder=aa0010ff
input=e1e2ebff
match=f4aeffdd
selection=4d8efedd
selection-text=000000ff
selection-match=000000ff
counter=b1c6f7ff
border=424753ff